service:
  version:
    curl: v1
dubbo:
  enabled: true
  scan:
    base-packages: io.flomesh.demo.simple.dubbo
  registry:
    address: zookeeper://10.0.0.1:2181
grpc:
  server:
    port: -1 #disable grpc server
