apiVersion: apps/v1
kind: Deployment
metadata:
  name: fgw-dubbo-route
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fgw-dubbo-route
      version: v1
  template:
    metadata:
      labels:
        app: fgw-dubbo-route
        version: v1
    spec:
      containers:
        - name: fgw
          image: cybwan/fgw-dubbo-demo:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 6666
            - containerPort: 6060
          command: ['pipy']
          args: [
            "--admin-port=6060",
            "fgw/src/main.js",
            "--threads=max",
            "--reuse-port",
            "--args",
            "--config",
            "/dubbo-route.yaml",
          ]
          #resources:
          #  requests:
          #    cpu: "2"
          #    memory: "2Gi"
          #  limits:
          #    cpu: "2"
          #    memory: "2Gi"