apiVersion: apps/v1
kind: Deployment
metadata:
  name: fgw-dubbo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fgw-dubbo-server
      version: v1
  template:
    metadata:
      labels:
        app: fgw-dubbo-server
        version: v1
    spec:
      containers:
        - name: server
          image: cybwan/fgw-dubbo-demo:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 20880
          command: ['pipy']
          args: [
            "/dubbo-server.js",
            "--threads=max",
            "--reuse-port",
          ]
          #resources:
          #  requests:
          #    cpu: "1"
          #    memory: "1Gi"
          #  limits:
          #    cpu: "1"
          #    memory: "1Gi"