eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    gZipContent: false
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
---
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL}
spring:
  config:
    activate:
      on-profile: eureka