name: Release smartdns-eureka-httpbin-demo

on:
  push:
    branches:
      - smartdns-eureka-httpbin-demo

jobs:
  version:
    name: Set Version from git ref
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - id: version
        run: echo "::set-output name=version::$(sed 's#^refs/tags/\(.*\)#\1#' <<< '${{ github.ref }}')"

  demo-images:
    name: Demo Docker Images
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Login to DockerHub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.RELEASE_DOCKER_USER }}
          password: ${{ secrets.RELEASE_DOCKER_PASS }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v5.7.0
        with:
          images: ${{ secrets.RELEASE_REGISTRY }}/smartdns-eureka-httpbin-demo
          tags: latest

      - name: Build and Push
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}