name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  eureka-images:
    name: Eureka Demo Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        id: [ "bookbuyer", "bookthief", "bookstore", "bookwarehouse", "httpbin", "curl" ]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.RELEASE_DOCKER_USER }}
          password: ${{ secrets.RELEASE_DOCKER_PASS }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker meta - ${{ matrix.id }}
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v5.3.0
        with:
          images: ${{ secrets.RELEASE_REGISTRY }}/springboot-demo
          tags: ${{ matrix.id }}.eureka

      - name: Build and Push - ${{ matrix.id }}
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: dockerfiles/Dockerfile.eureka
          platforms: linux/amd64,linux/arm64
          build-args: |
            SERVICE_NAME=${{ matrix.id }}
          push: ${{ (github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v') || github.ref == format('refs/heads/{0}', github.event.repository.default_branch) )) }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}